import type { LabeledExample } from "./naive-bayes";

/**
 * Hand-authored, labeled training set for the Revenue/Expense Naive Bayes
 * classifier. These are our own examples — written to cover varied real-world
 * financial phrasing across many departments and scenarios so the classifier
 * generalizes beyond exact keyword matches. Each row is a (text, label) pair;
 * the model learns word-likelihoods per class from these labels.
 *
 * Size is intentionally in the low hundreds: Naive Bayes is a high-bias,
 * low-variance model that performs well on modest labeled data — unlike deep
 * models, it does not need millions of examples. See naive-bayes.ts.
 */
export const FINANCIAL_TRAINING_DATA: LabeledExample[] = [
    // ============================ REVENUE ============================
    { text: "Sales department generated fifty thousand dollars in revenue this quarter", label: "REVENUE" },
    { text: "Product sales brought in strong income from new customers", label: "REVENUE" },
    { text: "Client payment received for consulting services rendered", label: "REVENUE" },
    { text: "Subscription revenue grew steadily across all pricing tiers", label: "REVENUE" },
    { text: "Invoice paid in full by enterprise customer", label: "REVENUE" },
    { text: "Monthly recurring revenue increased due to new signups", label: "REVENUE" },
    { text: "Sales team closed several large deals generating significant income", label: "REVENUE" },
    { text: "Retail division reported strong quarterly sales figures", label: "REVENUE" },
    { text: "Licensing fees collected from partner integration", label: "REVENUE" },
    { text: "E-commerce store sold record units this month", label: "REVENUE" },
    { text: "Contract signed with new client worth substantial annual value", label: "REVENUE" },
    { text: "Interest income earned on cash reserves", label: "REVENUE" },
    { text: "Service fees collected from onboarding new accounts", label: "REVENUE" },
    { text: "Product line generated healthy profit margins from sales", label: "REVENUE" },
    { text: "Customer renewed annual subscription contract", label: "REVENUE" },
    { text: "Export sales to overseas markets increased revenue", label: "REVENUE" },
    { text: "Ad revenue from sponsored placements grew this period", label: "REVENUE" },
    { text: "Wholesale orders brought in additional income", label: "REVENUE" },
    { text: "App store purchases contributed to monthly earnings", label: "REVENUE" },
    { text: "Consulting engagement completed and billed to client", label: "REVENUE" },
    { text: "Franchise royalties received from regional partners", label: "REVENUE" },
    { text: "Ticket sales for the annual conference exceeded projections", label: "REVENUE" },
    { text: "New enterprise deal closed by the sales team", label: "REVENUE" },
    { text: "Recurring billing charged successfully to active customers", label: "REVENUE" },
    { text: "Sponsorship deal signed bringing in new funds", label: "REVENUE" },
    { text: "Commission earned on referral partnership", label: "REVENUE" },
    { text: "Upsell to existing customer increased account value", label: "REVENUE" },
    { text: "Rental income collected from leased office space", label: "REVENUE" },
    { text: "Gross merchandise value grew across the marketplace", label: "REVENUE" },
    { text: "Premium tier upgrades boosted total revenue", label: "REVENUE" },
    { text: "Quarterly earnings beat expectations driven by strong sales", label: "REVENUE" },
    { text: "Customer paid the outstanding balance on their account", label: "REVENUE" },
    { text: "Sales pipeline converted into closed won deals this month", label: "REVENUE" },
    { text: "Marketplace transaction fees added to total income", label: "REVENUE" },
    { text: "International distributor placed a large purchase order", label: "REVENUE" },
    { text: "Support contract renewal generated additional revenue", label: "REVENUE" },
    { text: "Retail store foot traffic converted to strong sales numbers", label: "REVENUE" },
    { text: "New product launch drove a spike in customer purchases", label: "REVENUE" },
    { text: "Annual contract value increased after expansion deal", label: "REVENUE" },
    { text: "Cash inflow from completed customer project", label: "REVENUE" },
    { text: "Gross revenue for the department rose year over year", label: "REVENUE" },
    { text: "Point of sale terminals processed record transaction volume", label: "REVENUE" },
    { text: "B2B partnership brought recurring monthly income", label: "REVENUE" },
    { text: "Sales incentive program drove higher unit sales", label: "REVENUE" },
    { text: "Trade show leads converted into paying customers", label: "REVENUE" },
    { text: "Deposits received from advance customer bookings", label: "REVENUE" },
    { text: "Digital download sales grew after the marketing push", label: "REVENUE" },
    { text: "Membership dues collected from renewing subscribers", label: "REVENUE" },
    { text: "Cross-sell campaign added revenue from existing clients", label: "REVENUE" },
    { text: "Volume discount deal still increased total sales value", label: "REVENUE" },
    { text: "Reseller channel delivered strong quarterly bookings", label: "REVENUE" },
    { text: "Enterprise license agreement renewed at a higher tier", label: "REVENUE" },
    { text: "Pay-per-use billing generated income from active usage", label: "REVENUE" },
    { text: "Seasonal promotion drove a surge in online orders", label: "REVENUE" },
    { text: "Milestone payment received on the delivery contract", label: "REVENUE" },
    { text: "Advertising partners paid for banner placements", label: "REVENUE" },
    { text: "Gift card sales added to the holiday revenue total", label: "REVENUE" },
    { text: "Data licensing agreement produced a lump sum payment", label: "REVENUE" },
    { text: "Warranty upgrade purchases added incremental income", label: "REVENUE" },
    { text: "Government tender awarded generating a large contract", label: "REVENUE" },
    { text: "Client settled their invoice ahead of the due date", label: "REVENUE" },
    { text: "Recurring maintenance plan billed to the customer base", label: "REVENUE" },
    { text: "New market entry produced first sales this quarter", label: "REVENUE" },
    { text: "Bulk order from a wholesale buyer boosted turnover", label: "REVENUE" },
    { text: "Platform commission earned on third party transactions", label: "REVENUE" },
    { text: "Customer expanded their seat count increasing the contract", label: "REVENUE" },
    { text: "Subscription upgrades pushed monthly income higher", label: "REVENUE" },
    { text: "Product bundle sold well during the launch week", label: "REVENUE" },
    { text: "Late renewal finally closed adding to revenue", label: "REVENUE" },
    { text: "Affiliate-driven signups converted into paid plans", label: "REVENUE" },
    { text: "Regional office reported its best sales month yet", label: "REVENUE" },
    { text: "Installation service fee charged to the new client", label: "REVENUE" },
    { text: "Annual maintenance contract billed upfront", label: "REVENUE" },
    { text: "Customer top-up payment credited to the account", label: "REVENUE" },
    { text: "Trade-in program still netted positive sales revenue", label: "REVENUE" },
    { text: "Live event registrations sold out generating strong income", label: "REVENUE" },
    { text: "Distribution partner remitted the quarterly earnings share", label: "REVENUE" },
    { text: "Freemium conversions produced new paid subscriptions", label: "REVENUE" },
    { text: "Custom development project invoiced to the client", label: "REVENUE" },
    { text: "Retail chain reordered stock boosting wholesale income", label: "REVENUE" },
    { text: "Online course enrollments generated tuition revenue", label: "REVENUE" },
    { text: "White-label deal signed with a new business partner", label: "REVENUE" },
    { text: "Renewal wave lifted recurring revenue for the quarter", label: "REVENUE" },
    { text: "Marketplace seller fees collected from active vendors", label: "REVENUE" },
    { text: "Customer prepaid for a full year of service", label: "REVENUE" },
    { text: "Add-on module purchases increased average deal size", label: "REVENUE" },
    { text: "Dividend income received from a minority investment", label: "REVENUE" },
    { text: "Consulting retainer billed monthly to the key account", label: "REVENUE" },
    { text: "Referral partner drove several new customer signings", label: "REVENUE" },
    { text: "Holiday campaign produced record daily sales", label: "REVENUE" },
    { text: "Enterprise renewal secured at expanded scope and value", label: "REVENUE" },

    // ============================ EXPENSE ============================
    { text: "Marketing spent twelve thousand dollars on advertising campaigns", label: "EXPENSE" },
    { text: "Office rent paid for the downtown headquarters", label: "EXPENSE" },
    { text: "Payroll costs increased due to new hires this quarter", label: "EXPENSE" },
    { text: "Software subscription fees charged monthly to the engineering team", label: "EXPENSE" },
    { text: "Travel expenses submitted for the sales conference", label: "EXPENSE" },
    { text: "Equipment purchase for the new office setup", label: "EXPENSE" },
    { text: "Legal fees paid for contract review services", label: "EXPENSE" },
    { text: "Utility bills for the warehouse facility", label: "EXPENSE" },
    { text: "Consulting fees paid to external advisors", label: "EXPENSE" },
    { text: "Insurance premiums due for company liability coverage", label: "EXPENSE" },
    { text: "Cloud hosting costs rose due to increased server usage", label: "EXPENSE" },
    { text: "Employee benefits and healthcare costs for the HR department", label: "EXPENSE" },
    { text: "Raw material costs increased for manufacturing operations", label: "EXPENSE" },
    { text: "Advertising spend on social media platforms this month", label: "EXPENSE" },
    { text: "Freight and shipping costs for product delivery", label: "EXPENSE" },
    { text: "Training program costs for onboarding new employees", label: "EXPENSE" },
    { text: "Maintenance costs for factory equipment repairs", label: "EXPENSE" },
    { text: "Office supplies purchased for daily operations", label: "EXPENSE" },
    { text: "Contractor invoices paid for the development project", label: "EXPENSE" },
    { text: "Recruitment agency fees for filling open positions", label: "EXPENSE" },
    { text: "Bank fees and transaction charges for the month", label: "EXPENSE" },
    { text: "Depreciation expense recorded for company vehicles", label: "EXPENSE" },
    { text: "IT department spent on new laptops for the team", label: "EXPENSE" },
    { text: "Customer support outsourcing costs for the quarter", label: "EXPENSE" },
    { text: "Research and development costs for the new prototype", label: "EXPENSE" },
    { text: "Security services contract renewed for office building", label: "EXPENSE" },
    { text: "Payroll taxes withheld and remitted this pay period", label: "EXPENSE" },
    { text: "Facilities team spent on HVAC system repairs", label: "EXPENSE" },
    { text: "Print materials and signage costs for the trade show", label: "EXPENSE" },
    { text: "Software licensing renewal for design tools", label: "EXPENSE" },
    { text: "Overtime pay issued to warehouse staff", label: "EXPENSE" },
    { text: "Corporate credit card charges for team lunches", label: "EXPENSE" },
    { text: "Vehicle fuel costs for the delivery fleet", label: "EXPENSE" },
    { text: "Compliance audit fees paid to external auditors", label: "EXPENSE" },
    { text: "Data storage costs increased with growing customer base", label: "EXPENSE" },
    { text: "Employee relocation costs for the new regional office", label: "EXPENSE" },
    { text: "Packaging materials cost for outgoing shipments", label: "EXPENSE" },
    { text: "Customer refund issued for a returned order", label: "EXPENSE" },
    { text: "Late payment penalty charged by a vendor", label: "EXPENSE" },
    { text: "Server downtime incident required emergency contractor support", label: "EXPENSE" },
    { text: "Quarterly payroll run for the entire engineering team", label: "EXPENSE" },
    { text: "New office furniture purchased for the HR department", label: "EXPENSE" },
    { text: "Marketing agency retainer fee for the quarter", label: "EXPENSE" },
    { text: "Employee stock plan administration costs", label: "EXPENSE" },
    { text: "Warehouse lease payment for additional storage space", label: "EXPENSE" },
    { text: "IT security software subscription renewed annually", label: "EXPENSE" },
    { text: "Utility electricity charges for the manufacturing plant", label: "EXPENSE" },
    { text: "Sales team commission payouts for closed deals", label: "EXPENSE" },
    { text: "Domain and web hosting renewal fees", label: "EXPENSE" },
    { text: "Catering costs for the company town hall", label: "EXPENSE" },
    { text: "Professional membership dues for the finance staff", label: "EXPENSE" },
    { text: "Repair costs for the delivery truck breakdown", label: "EXPENSE" },
    { text: "Advertising billboard rental for the campaign", label: "EXPENSE" },
    { text: "Cleaning and janitorial services for the office", label: "EXPENSE" },
    { text: "Conference sponsorship fee paid to the organizer", label: "EXPENSE" },
    { text: "Subscription to market research reports renewed", label: "EXPENSE" },
    { text: "Shipping insurance for high value international freight", label: "EXPENSE" },
    { text: "Employee wellness program costs for the quarter", label: "EXPENSE" },
    { text: "Bonus payments distributed to top performers", label: "EXPENSE" },
    { text: "Cost of goods sold rose with higher supplier prices", label: "EXPENSE" },
    { text: "Payment gateway processing fees deducted this month", label: "EXPENSE" },
    { text: "Office internet and telephone service charges", label: "EXPENSE" },
    { text: "Trademark registration fees paid to the legal office", label: "EXPENSE" },
    { text: "Warehouse forklift maintenance and servicing cost", label: "EXPENSE" },
    { text: "Employee severance package paid on departure", label: "EXPENSE" },
    { text: "Digital ad platform spend exceeded the monthly budget", label: "EXPENSE" },
    { text: "Accounting software annual license fee", label: "EXPENSE" },
    { text: "Property tax payment for the company premises", label: "EXPENSE" },
    { text: "Cost of raw components for the assembly line", label: "EXPENSE" },
    { text: "Team offsite venue and accommodation costs", label: "EXPENSE" },
    { text: "Contractor day rate billed for the migration work", label: "EXPENSE" },
    { text: "Health insurance renewal premium for all staff", label: "EXPENSE" },
    { text: "Courier charges for document delivery", label: "EXPENSE" },
    { text: "Penalty fee for early lease termination", label: "EXPENSE" },
    { text: "Water and sewage utility bill for the facility", label: "EXPENSE" },
    { text: "Software developer contractor payment for the sprint", label: "EXPENSE" },
    { text: "Marketing swag and promotional giveaways cost", label: "EXPENSE" },
    { text: "Recruitment job board posting fees", label: "EXPENSE" },
    { text: "Data center colocation monthly charge", label: "EXPENSE" },
    { text: "Fleet vehicle insurance premium payment", label: "EXPENSE" },
    { text: "Legal settlement paid to resolve a dispute", label: "EXPENSE" },
    { text: "Office coffee and pantry restocking costs", label: "EXPENSE" },
    { text: "Annual audit and tax filing service fees", label: "EXPENSE" },
    { text: "Cloud backup and disaster recovery subscription", label: "EXPENSE" },
    { text: "Equipment lease payment for manufacturing machinery", label: "EXPENSE" },
    { text: "Staff training workshop facilitator fees", label: "EXPENSE" },
    { text: "Import duties paid on incoming raw materials", label: "EXPENSE" },
    { text: "Customer acquisition cost from paid advertising", label: "EXPENSE" },
    { text: "Consulting firm engagement for process improvement", label: "EXPENSE" },
    { text: "Office renovation and fit-out contractor costs", label: "EXPENSE" },
    { text: "Payroll processing service monthly fee", label: "EXPENSE" },
    { text: "Warehouse security guard staffing costs", label: "EXPENSE" },
];
