import type { LabeledExample } from "./naive-bayes";

/**
 * Hand-authored training set for the Revenue/Expense Naive Bayes classifier.
 * These are our own labeled examples, not scraped or borrowed from any
 * dataset — written to cover varied real-world phrasing across departments
 * so the classifier generalizes beyond exact keyword matches.
 */
export const FINANCIAL_TRAINING_DATA: LabeledExample[] = [
    // --- REVENUE ---
    { text: "Sales department generated fifty thousand dollars in revenue this quarter", label: "REVENUE" },
    { text: "Product sales brought in strong income from new customers", label: "REVENUE" },
    { text: "Client payment received for consulting services rendered", label: "REVENUE" },
    { text: "Subscription revenue grew steadily across all pricing tiers", label: "REVENUE" },
    { text: "Invoice paid in full by enterprise customer", label: "REVENUE" },
    { text: "Monthly recurring revenue increased due to new signups", label: "REVENUE" },
    { text: "Sales team closed several large deals generating significant income", label: "REVENUE" },
    { text: "Retail division reported strong quarterly sales figures", label: "REVENUE" },
    { text: "Licensing fees collected from partner integration", label: "REVENUE" },
    { text: "E-commerce store sold record units this month", label: "REVENUE" },
    { text: "Contract signed with new client worth substantial annual value", label: "REVENUE" },
    { text: "Interest income earned on cash reserves", label: "REVENUE" },
    { text: "Service fees collected from onboarding new accounts", label: "REVENUE" },
    { text: "Product line generated healthy profit margins from sales", label: "REVENUE" },
    { text: "Customer renewed annual subscription contract", label: "REVENUE" },
    { text: "Export sales to overseas markets increased revenue", label: "REVENUE" },
    { text: "Ad revenue from sponsored placements grew this period", label: "REVENUE" },
    { text: "Wholesale orders brought in additional income", label: "REVENUE" },
    { text: "App store purchases contributed to monthly earnings", label: "REVENUE" },
    { text: "Consulting engagement completed and billed to client", label: "REVENUE" },
    { text: "Franchise royalties received from regional partners", label: "REVENUE" },
    { text: "Ticket sales for the annual conference exceeded projections", label: "REVENUE" },
    { text: "New enterprise deal closed by the sales team", label: "REVENUE" },
    { text: "Recurring billing charged successfully to active customers", label: "REVENUE" },
    { text: "Sponsorship deal signed bringing in new funds", label: "REVENUE" },
    { text: "Commission earned on referral partnership", label: "REVENUE" },
    { text: "Upsell to existing customer increased account value", label: "REVENUE" },
    { text: "Rental income collected from leased office space", label: "REVENUE" },
    { text: "Gross merchandise value grew across the marketplace", label: "REVENUE" },
    { text: "Premium tier upgrades boosted total revenue", label: "REVENUE" },
    { text: "Quarterly earnings beat expectations driven by strong sales", label: "REVENUE" },
    { text: "Customer paid the outstanding balance on their account", label: "REVENUE" },
    { text: "Sales pipeline converted into closed won deals this month", label: "REVENUE" },
    { text: "Marketplace transaction fees added to total income", label: "REVENUE" },
    { text: "International distributor placed a large purchase order", label: "REVENUE" },
    { text: "Support contract renewal generated additional revenue", label: "REVENUE" },
    { text: "Retail store foot traffic converted to strong sales numbers", label: "REVENUE" },
    { text: "New product launch drove a spike in customer purchases", label: "REVENUE" },
    { text: "Affiliate program payouts were offset by higher referral sales", label: "REVENUE" },
    { text: "Annual contract value increased after expansion deal", label: "REVENUE" },
    { text: "Cash inflow from completed customer project", label: "REVENUE" },
    { text: "Gross revenue for the department rose year over year", label: "REVENUE" },
    { text: "Point of sale terminals processed record transaction volume", label: "REVENUE" },
    { text: "B2B partnership brought recurring monthly income", label: "REVENUE" },
    { text: "Sales incentive program drove higher unit sales", label: "REVENUE" },
    { text: "Trade show leads converted into paying customers", label: "REVENUE" },

    // --- EXPENSE ---
    { text: "Marketing spent twelve thousand dollars on advertising campaigns", label: "EXPENSE" },
    { text: "Office rent paid for the downtown headquarters", label: "EXPENSE" },
    { text: "Payroll costs increased due to new hires this quarter", label: "EXPENSE" },
    { text: "Software subscription fees charged monthly to the engineering team", label: "EXPENSE" },
    { text: "Travel expenses submitted for the sales conference", label: "EXPENSE" },
    { text: "Equipment purchase for the new office setup", label: "EXPENSE" },
    { text: "Legal fees paid for contract review services", label: "EXPENSE" },
    { text: "Utility bills for the warehouse facility", label: "EXPENSE" },
    { text: "Consulting fees paid to external advisors", label: "EXPENSE" },
    { text: "Insurance premiums due for company liability coverage", label: "EXPENSE" },
    { text: "Cloud hosting costs rose due to increased server usage", label: "EXPENSE" },
    { text: "Employee benefits and healthcare costs for the HR department", label: "EXPENSE" },
    { text: "Raw material costs increased for manufacturing operations", label: "EXPENSE" },
    { text: "Advertising spend on social media platforms this month", label: "EXPENSE" },
    { text: "Freight and shipping costs for product delivery", label: "EXPENSE" },
    { text: "Training program costs for onboarding new employees", label: "EXPENSE" },
    { text: "Maintenance costs for factory equipment repairs", label: "EXPENSE" },
    { text: "Office supplies purchased for daily operations", label: "EXPENSE" },
    { text: "Contractor invoices paid for the development project", label: "EXPENSE" },
    { text: "Recruitment agency fees for filling open positions", label: "EXPENSE" },
    { text: "Bank fees and transaction charges for the month", label: "EXPENSE" },
    { text: "Depreciation expense recorded for company vehicles", label: "EXPENSE" },
    { text: "IT department spent on new laptops for the team", label: "EXPENSE" },
    { text: "Customer support outsourcing costs for the quarter", label: "EXPENSE" },
    { text: "Research and development costs for the new prototype", label: "EXPENSE" },
    { text: "Security services contract renewed for office building", label: "EXPENSE" },
    { text: "Payroll taxes withheld and remitted this pay period", label: "EXPENSE" },
    { text: "Facilities team spent on HVAC system repairs", label: "EXPENSE" },
    { text: "Print materials and signage costs for the trade show", label: "EXPENSE" },
    { text: "Software licensing renewal for design tools", label: "EXPENSE" },
    { text: "Overtime pay issued to warehouse staff", label: "EXPENSE" },
    { text: "Corporate credit card charges for team lunches", label: "EXPENSE" },
    { text: "Vehicle fuel costs for the delivery fleet", label: "EXPENSE" },
    { text: "Compliance audit fees paid to external auditors", label: "EXPENSE" },
    { text: "Data storage costs increased with growing customer base", label: "EXPENSE" },
    { text: "Employee relocation costs for the new regional office", label: "EXPENSE" },
    { text: "Packaging materials cost for outgoing shipments", label: "EXPENSE" },
    { text: "Customer refund issued for a returned order", label: "EXPENSE" },
    { text: "Late payment penalty charged by a vendor", label: "EXPENSE" },
    { text: "Server downtime incident required emergency contractor support", label: "EXPENSE" },
    { text: "Quarterly payroll run for the entire engineering team", label: "EXPENSE" },
    { text: "New office furniture purchased for the HR department", label: "EXPENSE" },
    { text: "Marketing agency retainer fee for the quarter", label: "EXPENSE" },
    { text: "Employee stock plan administration costs", label: "EXPENSE" },
    { text: "Warehouse lease payment for additional storage space", label: "EXPENSE" },
    { text: "IT security software subscription renewed annually", label: "EXPENSE" },
];
